select SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
from ONLINE_SALE
where SALES_DATE between "2022-03-01" and "2022-03-31"

union all

select SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
from OFFLINE_SALE
where year(SALES_DATE) = "2022" and month(SALES_DATE) = "3"


order by SALES_DATE asc, PRODUCT_ID asc, USER_ID asc