# LEFT JOIN A = B
# A의 모든행을 B에 가져다줌

# RIGHT JOIN A = B
# B의 모든 행을 A에 가져다줌

SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA A
LEFT JOIN ECOLI_DATA B ON A.PARENT_ID = B.ID
WHERE A.GENOTYPE & B.GENOTYPE = B.GENOTYPE
ORDER BY A.ID ASC;
