select year(DIFFERENTIATION_DATE) as YEAR,
    (
    select max(SIZE_OF_COLONY)
    from ECOLI_DATA
    where year(DIFFERENTIATION_DATE) = year(A.DIFFERENTIATION_DATE)
    ) - A.SIZE_OF_COLONY AS YEAR_DEV, ID

FROM ECOLI_DATA A
ORDER BY YEAR, YEAR_DEV;